services:
  db-1:
    image: postgres:13
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: v9023aSH
      POSTGRES_DB: terminals
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web-1:
    build: .
    command: /wait-for-it.sh db-1:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - db-1
    environment:
      - DATABASE_URL=postgresql+asyncpg://server:v9023aSH@db-1:5432/terminals
      - PUBLIC_KEY_PATH=public_key.pem
      - PRIVATE_KEY_PATH=private_key.pem
      - ALGORITHM=RS256
      - SECRET_KEY=IOUFh432sad%f1c7243gJ-jisdf%gsfvd3q23/asd&asdc
      - ACCESS_TOKEN_EXPIRE_MINUTES=600
      - SPECIAL_TOKEN=sokd%fwew324r-vek&rfm2-sdvm2f-vsokdk#vssdf
      - EMPTY_BOTTLE_ID=-1
    volumes:
      - images:/images
      - logs:/logs

volumes:
  postgres_data:
  images:
    driver: local
  logs:
    driver: local