services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: v9023aSH
      POSTGRES_DB: terminals
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: /wait-for-it.sh db:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://server:v9023aSH@localhost:5432/terminals

volumes:
  postgres_data:

